#define SECRET_SSID "raspi-webgui"
#define SECRET_PASS "ChangeMe"
//#define SECRET_SSID "perso"
//#define SECRET_PASS "pegase123456789"
//#define SECRET_SSID "Livebox-4B30"
//#define SECRET_PASS "UAQpEqiRUtAoFs2GFU"
